"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-10-06

Bootstrap migration:
Uses SQLAlchemy metadata to create all 29 domain tables.
After the schema stabilizes, replace this with an explicit autogenerated migration.
"""
from alembic import op

from app.db.base import Base
import app.db.models  # noqa: F401

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
